import time
import threading
from main import *
from sell import *
import sys
from slack_bot import post_error_to_slack
import warnings
import traceback
warnings.filterwarnings("ignore", category=UserWarning, module='bs4')



description = """
This is a signaling proposal to update Stride’s tokenomics by introducing a buyback and burn mechanism for the STRD token using Stride protocol fees. The mechanism will utilize 85% of Stride’s protocol fee to buy back STRD and send it to a burn address: stride1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsgqrn3 (See Appendix below for burn address details).

With the current state of protocol fees this would result in approximately 923,000 STRD (1% of current max supply) being bought back and burned per year.

Background

Stride collects a 10% fee on staking rewards generated by tokens liquid staked with the protocol. Since launch, Stride’s annualized protocol fee has fluctuated from $450,000 USD to $5,000,000 USD based on the market valuations of the underlying staked tokens.

Stride governance controls how the protocol uses its protocol fee, and has currently elected to divert the majority of protocol fees directly to STRD stakers, under the justification that this would encourage additional tokens to be staked, increasing Stride’s bonded ratio and overall security.

However, since that time some significant changes have been made to the Stride protocol, including the transition to consuming interchain security from the Cosmos Hub. Since staked STRD tokens no longer actively contribute to the protocol’s security, it is likely that Stride is overpaying for delegated stake. While staking continues to be a valuable service provided by tokenholders due to the governance powers it confers, it makes sense to revisit the protocol fee allocation model to ensure that it benefits the Stride protocol and ecosystem. This is especially true because inflationary STRD emissions will continue to flow to staked STRD.

Rationale

This proposal, if passed, will redirect the current protocol fee allocated to stakers and instead utilize it to buy back and burn STRD.

The current landscape of Stride tokenholders is far more varied than it was when proposal 8 was passed in late 2022. At the time, it felt imperative to encourage a large movement of STRD to stake to help bolster protocol security and reduce the low overall bonding rate. Today, staking remains important for governance, but there are other ecosystem participants that protocol fees could benefit. This includes stakers, LPs, ATOM stakers earning STRD emissions from ICS fees, and more.

Allocating protocol fees toward a token buyback and burn program ensures that all of these stakeholders are rewarded equally. 

Current Protocol Fee Allocation

Currently, Stride’s protocol fee is allocated as follows:

15% to the Cosmos Hub as payment for interchain security (Proposal 201)
85% to Stride governors and STRD stakers (Proposal 8)
5% of this accrues to the Stride community pool (Proposal 223)
Additionally, Stride governance has approved two protocol fee carve outs that share / reduce protocol fees under certain circumstances:

Stride rewards share program (Proposal 246)
dYdX POL fee reduction (Proposal 234)
Proposed Protocol Fee Allocation

This proposal seeks to redirect all of the protocol fees currently allocated toward Stride governors and STRD stakers towards the buying back and burning of STRD. Rather than being liquid staked and distributed, the underlying staking reward token commissions will take the following path:

Step 1: Tokens are sent to Osmosis or other liquid market (may be asset-specific)
Step 2: Tokens are swapped for STRD
Step 3: STRD is IBC transferred back to the Stride chain burn address
This will all be handled non-custodially via Stride’s interchain accounts on the respective host zones, and will closely resemble the current staking reward swapping mechanism employed for stDYDX.

At current prices, this protocol fee use case would result in approximately 923,524 STRD (approximately 1% of the max supply) being bought back and burned per year. This number is purely an estimate based on publicly available data, and is subject to change as protocol fees fluctuate.

The protocol fee allocation if this proposal passes is:

15% to the Cosmos Hub as payment for interchain security
85% used to buy back and burn STRD (protocol fees allocated to the Stride reward share program will first be deducted from this amount).
Implementation

This proposal is not executable. If passed, this proposal will be implemented via a subsequent software upgrade with core codebase changes enabling the buyback and burn mechanism. The timeline for implementation is expected to be approximately 4-6 weeks, but is subject to change based on development timelines.

Appendix - Burn Address Details

This proposal also designates stride1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqsgqrn3 as the official Stride burn address.

Cosmos SDK chains do not have a pre-designated burn address. EVM chains like Ethereum use the null address (0x0000000000000000000000000000000000000000) as a burn address. A Bech32 equivalent address on Stride can be derived and verified using the following CLI query:

image

In theory, this address does have a private key, but it is unknown. This method is also used by a number of other chains to create a burn address on the same private key, including Osmosis (h/t Johnny Wyles at Osmosis for this idea).

In order to have the address properly function as a burn address, it will need to be excluded from supply queries. This functionality will be included in the software upgrade that implements the burn mechanism. When the upgrade goes live, tokens sent to that address will be effectively removed from the token supply and burned forever.
"""


def scan_proposals():
    counter = 0
    db, app = create_firebase_client()
    store_data(db)
    summary_obj = Summarization("mistral")
    sentiment_analyzer = FinBERTSentiment()
    
    while True:
        try:
            proposal_dict = download_and_save_proposal(db)
            new_row_df = check_new_post(proposal_dict)
            
            new_row_df = {
                'post_id': 'uniswap-1',
                'coin' : 'aave',
                'timestamp': '2024-11-12',
                'description': description,
                'discussion_link' : 'https://commonwealth.im/stride/discussion/25027-stride-tokenomics-update-allocate-protocol-fees-to-buy-back-and-burn-strd'
            }
            new_row_df = pd.DataFrame([new_row_df])   
            
            trigger_trade(new_row_df, summary_obj, sentiment_analyzer)
            
            counter += 1
        
        except Exception as e:
            print("Error running scan proposal:", e)
            post_error_to_slack(str(traceback.format_exc()))
        
        # Countdown timer for 2 minutes (120 seconds)
        countdown_time = 1 * 60  # 120 seconds
        for remaining in range(countdown_time, 0, -1):
            sys.stdout.write("\rNext scan in: {:02d}:{:02d}".format(remaining // 60, remaining % 60))
            sys.stdout.flush()
            time.sleep(1)
        
        print("\n")  # Move to the next line after the countdown

    close_firebase_client(app)


if __name__ == "__main__":
    scan_proposals()


